name: ðŸŽ‰ Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM
        run: corepack enable

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Set Timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "Asia/Shanghai" | sudo tee /etc/timezone
          date
        shell: bash

      - name: Playwright install
        run: npx playwright install

      - name: Build
        run: nr build

      - name: Unit Test
        run: nr test:unit

      - name: Set npmrc for components
        run: |
          for package in $(find components/* -maxdepth 1 -type d); do
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ${package}/.npmrc
          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for root preset
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > preset/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for root utils
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > utils/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for root packages
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: nr publish:script

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
